window.__INV__ = [ 
  [
  {
    "id": "",
    "name": "Ultra Aurora 06",
    "vendor": "Glitter Unique",
    "category": "Pigment",
    "finish": "Interference",
    "color": "Blue",
    "particle_size_microns": "10-20",
    "solvent_safe": true,
    "weight_g": 5.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "GU-88231",
    "order_date": "2025-08-10",
    "location": "Pigments Bin A",
    "notes": "fine overlay shimmer",
    "image_url": "images/ua06.jpg"
  },
  {
    "id": "",
    "name": "Glitter Suspension Base",
    "vendor": "Glitter Unique",
    "category": "Base",
    "finish": "Suspension",
    "color": "Clear",
    "particle_size_microns": "",
    "solvent_safe": "",
    "weight_g": null,
    "volume_ml": 118.0,
    "price_usd": null,
    "order_id": "GU-88231",
    "order_date": "2025-08-10",
    "location": "Bases Shelf",
    "notes": "1/4 pint bottle",
    "image_url": "images/gu_base.jpg"
  },
  {
    "id": "",
    "name": "Spectraflair 35",
    "vendor": "Spectraflair4u",
    "category": "Special Effect",
    "finish": "Holographic",
    "color": "Silver",
    "particle_size_microns": "35",
    "solvent_safe": true,
    "weight_g": 2.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "S4U-12071",
    "order_date": "2025-08-31",
    "location": "Special FX",
    "notes": "premixed carrier",
    "image_url": "images/sf35.jpg"
  },
  {
    "id": "",
    "name": "ColorFlair4U White",
    "vendor": "Spectraflair4u",
    "category": "Pigment",
    "finish": "Pearl",
    "color": "White",
    "particle_size_microns": "",
    "solvent_safe": true,
    "weight_g": 5.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "S4U-12071",
    "order_date": "2025-08-31",
    "location": "Pigments Bin B",
    "notes": "",
    "image_url": "images/colorflair_white.jpg"
  },
  {
    "id": "",
    "name": "Kaleidoshift Zephyr",
    "vendor": "SolarColorDust",
    "category": "Pigment",
    "finish": "Multichrome",
    "color": "Blue/Green/Purple",
    "particle_size_microns": "",
    "solvent_safe": true,
    "weight_g": 2.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "SCD-7719",
    "order_date": "2025-08-15",
    "location": "Pigments Bin C",
    "notes": "",
    "image_url": "images/scd_zephyr.jpg"
  },
  {
    "id": "",
    "name": "Blue Glow Powder",
    "vendor": "Techno Glow",
    "category": "Pigment",
    "finish": "Glow",
    "color": "Blue",
    "particle_size_microns": "",
    "solvent_safe": true,
    "weight_g": 10.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "TG-5521",
    "order_date": "2025-08-12",
    "location": "Glow Drawer",
    "notes": "glow in the dark",
    "image_url": "images/tg_blue_glow.jpg"
  },
  {
    "id": "",
    "name": "Orange Magenta Purple Super Color Shift (Chameleon)",
    "vendor": "Just Pigments",
    "category": "Pigment",
    "finish": "Chameleon",
    "color": "Orange/Magenta/Purple",
    "particle_size_microns": "",
    "solvent_safe": true,
    "weight_g": 2.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "JP-54021",
    "order_date": "2025-08-24",
    "location": "JP Drawer",
    "notes": "sample",
    "image_url": "images/jp_chameleon_orange_magenta_purple.jpg"
  },
  {
    "id": "",
    "name": "Orange Magenta Teal Super Color Shift (Chameleon)",
    "vendor": "Just Pigments",
    "category": "Pigment",
    "finish": "Chameleon",
    "color": "Orange/Magenta/Teal",
    "particle_size_microns": "",
    "solvent_safe": true,
    "weight_g": 2.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "JP-54021",
    "order_date": "2025-08-24",
    "location": "JP Drawer",
    "notes": "sample",
    "image_url": "images/jp_chameleon_orange_magenta_teal.jpg"
  },
  {
    "id": "",
    "name": "Blue Green Yellow Super Color Shift (Chameleon)",
    "vendor": "Just Pigments",
    "category": "Pigment",
    "finish": "Chameleon",
    "color": "Blue/Green/Yellow",
    "particle_size_microns": "",
    "solvent_safe": true,
    "weight_g": 2.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "JP-54021",
    "order_date": "2025-08-24",
    "location": "JP Drawer",
    "notes": "sample",
    "image_url": "images/jp_chameleon_bgy.jpg"
  },
  {
    "id": "",
    "name": "Fine White Satin",
    "vendor": "Just Pigments",
    "category": "Pigment",
    "finish": "Pearl",
    "color": "White",
    "particle_size_microns": "5-25",
    "solvent_safe": true,
    "weight_g": 30.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "JP-54021",
    "order_date": "2025-08-24",
    "location": "JP Drawer",
    "notes": "",
    "image_url": "images/jp_white_satin.jpg"
  },
  {
    "id": "",
    "name": "Satin Gold",
    "vendor": "Just Pigments",
    "category": "Pigment",
    "finish": "Pearl",
    "color": "Gold",
    "particle_size_microns": "",
    "solvent_safe": true,
    "weight_g": 2.0,
    "volume_ml": null,
    "price_usd": null,
    "order_id": "JP-54021",
    "order_date": "2025-08-24",
    "location": "JP Drawer",
    "notes": "sample",
    "image_url": "images/jp_satin_gold.jpg"
  }
]
];
